export const questionBank = {
  'JavaScript': [
      "Can you explain the difference between 'let', 'const', and 'var' in JavaScript?",
      "What is the event loop in JavaScript and how does it work?",
      "How would you describe closures in JavaScript?",
      "What's the difference between synchronous and asynchronous code in JavaScript?",
      "What are promises in JavaScript? How do they work?",
      "Can you explain the difference between `null` and `undefined`?",
      "How does JavaScript handle memory management?",
      "What is the difference between deep copy and shallow copy in JavaScript?",
      "What are arrow functions, and how are they different from regular functions?",
      "How does JavaScript handle hoisting?",
      "What is the difference between `==` and `===`?",
      "Can you explain the concept of prototypal inheritance in JavaScript?",
      "What is the purpose of the `bind()`, `call()`, and `apply()` methods in JavaScript?",
      "How does JavaScript handle asynchronous operations with async/await?",
      "What is event delegation in JavaScript?",
      "Explain how `this` works in JavaScript.",
      "What are ES6 modules and how do they work?"
  ],
  'Python': [
      "How do you handle exceptions in Python?",
      "What are Python generators and how do they work?",
      "Can you explain Python decorators?",
      "What's the difference between a list and a tuple in Python?",
      "How does Python manage memory?",
      "What are list comprehensions in Python?",
      "What is the difference between `deepcopy` and `copy` in Python?",
      "Explain the difference between `is` and `==` in Python.",
      "What is the Global Interpreter Lock (GIL) in Python?",
      "What are lambda functions in Python?",
      "How do you implement multithreading in Python?",
      "What are the differences between Python 2 and Python 3?",
      "How does Python's garbage collection work?",
      "Explain the use of the `with` statement in Python.",
      "What are f-strings in Python?",
      "What are the different types of Python inheritance?"
  ],
  'React': [
      "What is reconciliation in React?",
      "What are the benefits of using React over vanilla JavaScript?",
      "How do you optimize React application performance?",
      "What is the difference between controlled and uncontrolled components?",
      "What is the role of keys in React lists?",
      "How do you handle forms in React?",
      "What are portals in React?",
      "What are the differences between React's class components and functional components?",
      "How does React handle events differently from HTML?",
      "What is React Suspense?",
      "How do you handle side effects in React?",
      "What is lazy loading in React?",
      "How does server-side rendering (SSR) work in React?",
      "What is the purpose of `useReducer` hook?",
      "How do you manage global state in React applications?",
      "What is a higher-order component in React?",
      "How do you implement code splitting in React?",
      "How does React handle conditional rendering?",
      "How does React handle state updates?",
      "What is the purpose of `React.memo`?",
      "How do you prevent unnecessary re-renders in React?",
      "What are synthetic events in React?",
      "How do you implement authentication in React?",
      "What is the significance of `useCallback` in React?",
      "How does React Router work?",
      "How does React handle context?",
      "What are custom hooks in React?",
      "What is progressive web app (PWA) in React?",
      "How do you fetch data in React applications?",
      "What is the role of Redux in React?",
      "Can you explain the virtual DOM concept in React?",
      "What are React hooks and why were they introduced?",
      "How do you manage state in a React application?",
      "What is JSX in React?",
      "What is the difference between controlled and uncontrolled components?",
      "What is the significance of `useEffect` in React?",
      "What are React fragments and why are they useful?",
      "How do React's reconciliation and rendering process work?",
      "How can you optimize the performance of a React application?",
      "What are higher-order components (HOC) in React?",
      "What is React Router and how does it work?",
      "How do you handle global state management in React?",
      "What is Context API in React?",
      "How does React handle component lifecycle methods?",
      "What are pure components in React?"
  ],
  'Full Stack': [
      "What modules or technologies do you typically use in full stack development?",
      "How do you handle communication between frontend and backend?",
      "What databases have you worked with in your full stack projects?",
      "How do you approach authentication in a full stack application?",
      "What is RESTful API, and how does it work?",
      "How does GraphQL compare to REST?",
      "How do you implement role-based access control in a full stack app?",
      "How do you secure sensitive data in a web application?",
      "How do you optimize API performance in a full stack application?",
      "What caching mechanisms do you use in full stack development?",
      "How do you handle database migrations in a full stack project?",
      "What are web sockets, and how do they work?",
      "What is the difference between monolithic and microservices architecture?",
      "How do you manage environment variables in full stack applications?",
      "What tools do you use for CI/CD in full stack development?"
  ],
  'Cybersecurity': [
      "What are the different types of encryption techniques?",
      "What is the difference between symmetric and asymmetric encryption?",
      "How does HTTPS ensure secure communication?",
      "What are common OWASP Top 10 security vulnerabilities?",
      "What is SQL injection and how do you prevent it?",
      "What are the differences between hashing and encryption?",
      "What is two-factor authentication (2FA) and how does it work?",
      "How do you secure API endpoints?",
      "What is Cross-Site Scripting (XSS) and how do you prevent it?",
      "What is the difference between penetration testing and vulnerability assessment?"
  ],
  'Machine Learning': [
      "What are the different types of machine learning?",
      "Explain bias-variance tradeoff in machine learning.",
      "What is the difference between supervised and unsupervised learning?",
      "What are overfitting and underfitting in machine learning?",
      "What are hyperparameters in machine learning?",
      "What is a neural network and how does it work?",
      "Explain the concept of backpropagation in neural networks.",
      "What is gradient descent and how does it work?",
      "What are activation functions in neural networks?",
      "What is transfer learning and when is it useful?"
  ],
  'DevOps': [
      "What is CI/CD and how does it work?",
      "What tools have you used for DevOps?",
      "What is containerization and how does Docker work?",
      "What are the benefits of using Kubernetes?",
      "How do you implement infrastructure as code?",
      "What is the difference between Jenkins and GitHub Actions?",
      "What are blue-green deployments?",
      "How do you ensure high availability in cloud applications?",
      "What are monitoring tools you use in DevOps?",
      "What is log aggregation, and why is it important?"
  ],
  'AI/ML': [
      "What is deep learning and how is it different from traditional ML?",
      "What is reinforcement learning?",
      "Explain the concept of a decision tree in machine learning.",
      "What is an autoencoder?",
      "How does a support vector machine (SVM) work?",
      "What is an adversarial attack in machine learning?",
      "How do convolutional neural networks (CNNs) work?",
      "What is the role of feature engineering in ML?",
      "What is an attention mechanism in deep learning?",
      "Explain BERT and its applications in NLP."
  ],
  'Blockchain': [
      "What is a blockchain and how does it work?",
      "What are smart contracts?",
      "What is the difference between public and private blockchains?",
      "What is Proof of Work vs Proof of Stake?",
      "How does consensus work in a blockchain?",
      "What are common blockchain use cases?",
      "How do NFTs work?",
      "What are the security challenges in blockchain technology?",
      "What is a 51% attack?",
      "What is the role of hashing in blockchain security?"
  ],
  'Default': [
      "Can you describe your problem-solving approach when facing a technical challenge?",
      "How do you stay updated with the latest technology trends?",
      "Describe a technical project you've worked on that you're proud of.",
      "How do you approach learning new technologies or frameworks?",
      "What was the most challenging bug you've fixed, and how did you solve it?",
      "How do you handle working under tight deadlines?",
      "What is your preferred development workflow?",
      "What tools do you use to improve productivity?",
      "Describe a time when you had to quickly learn a new technology.",
      "How do you handle disagreements in a development team?"
  ]
};

export default questionBank;